config/routes.rb
Rails.application.routes.draw do
  resources :notebooks do
    resources :chapters
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Root for authenticated users
  root to: 'notebooks#index'
  authenticate :user do
    root to: 'notebooks#index', as: :authenticated_root
    resources :notebooks
  end

  # Root for unauthenticated users (i.e., show login page)
  unauthenticated do
    root to: 'devise/sessions#new', as: :unauthenticated_root
  end

  # Custom login route
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :notebook

  validates :status, inclusion: {in: ['not-started', 'in-progress', 'complete']}

  STATUS_OPTIONS = [
    ['Not Started', 'not-started'],
    ['In Progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def complete?
    status == 'complete'
  end
  def in_progress?
    status == 'in-progress'
  end
  def not_started?
    status == 'not-started'
  end
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  has_many :chapters, dependent: :destroy
  belongs_to :user

  def status
    return 'not-started' if chapters.none?
    if chapters.all? { |chapter| chapter.complete?}
      'complete'
    elsif chapters.any? { |chapter| chapter.in_progress? || chapter.complete?}
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    total = chapters.count
    return 0 if total.zero?

    complete_chapters = chapters.count { |chapter| chapter.complete? }
    ((complete_chapters.to_f / total) * 100).round
  end
  def total_complete
    chapters.select { |chapter| chapter.complete?}.count
  end
  def total_chapters
    chapters.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notebooks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notebook
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET notebooks/1/chapters
  def index
    @chapters = @notebook.chapters
  end

  # GET notebooks/1/chapters/1
  def show
  end

  # GET notebooks/1/chapters/new
  def new
    @chapter = @notebook.chapters.build
  end

  # GET notebooks/1/chapters/1/edit
  def edit
  end

  # POST notebooks/1/chapters
  def create
    @chapter = @notebook.chapters.build(chapter_params)

    if @chapter.save
      redirect_to(@chapter.notebook)
    else
      render action: 'new'
    end
  end

  # PUT notebooks/1/chapters/1
  def update
    if @chapter.update(chapter_params)
      redirect_to notebook_chapter_path(@chapter.notebook, @chapter)
    else
      render action: 'edit'
    end
  end

  # DELETE notebooks/1/chapters/1
  def destroy
    @chapter.destroy

    redirect_to @notebook
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = current_user.notebooks.find(params[:notebook_id])
    end

    def set_chapter
      @chapter = @notebook.chapters.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chapter_params
      params.require(:chapter).permit(:name, :description, :status, :notebook_id)
    end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notebook, only: %i[ show edit update destroy ]

  # GET /notebooks or /notebooks.json
  def index
    @notebooks = current_user.notebooks
  end

  # GET /notebooks/1 or /notebooks/1.json
  def show
    @chapter = @notebook.chapters.build
  end

  # GET /notebooks/new
  def new
    @notebook = current_user.notebooks.build
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks or /notebooks.json
  def create
    @notebook = current_user.notebooks.build(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: "Notebook was successfully created." }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1 or /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: "Notebook was successfully updated." }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1 or /notebooks/1.json
  def destroy
    @notebook.destroy!

    respond_to do |format|
      format.html { redirect_to notebooks_path, status: :see_other, notice: "Notebook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = current_user.notebooks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notebook_params
      params.require(:notebook).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: [@chapter.notebook, @chapter]) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :status, value:'not-started' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Chapter::STATUS_OPTIONS %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', [@chapter.notebook, @chapter] %> |
<%= link_to 'Back', notebook_chapters_path(@chapter.notebook) %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notebook.chapters.each do |chapter| %>
  <tr>
    <td><%= chapter.name %></td>
    <td><%= chapter.description %></td>
    <td><%= chapter.status %></td>
    <td><%= link_to 'Show', [chapter.notebook, chapter] %></td>
    <td><%= link_to 'Edit', edit_notebook_chapter_path(chapter.notebook, chapter) %></td>
    <td><%= button_to 'Destroy', [chapter.notebook, chapter], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chapter', new_notebook_chapter_path(@notebook.id) %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', notebook_chapters_path(@chapter.notebook) %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chapter.name %>
</p>

<p>
  <b>Description:</b>
  <%= @chapter.description %>
</p>

<p>
  <b>Status:</b>
  <%= @chapter.status %>
</p>



<%= link_to 'Edit', edit_notebook_chapter_path(@chapter.notebook, @chapter) %> |
<%= link_to 'Back', @notebook %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Notes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <header>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/notebooks/_form.html.erb
<%= form_with(model: notebook) do |form| %>
  <% if notebook.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
        <% notebook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notebooks/_notebook.html.erb
<tr>
  <td><%= notebook.name %></td>
  <td><%= notebook.description %></td>
  <td><%= notebook.status %></td>
  <td><%= notebook.percent_complete %>%</td>
  <td><%= notebook.total_complete %>/<%= notebook.total_chapters %></td>
</tr>

app/views/notebooks/edit.html.erb
<% content_for :title, "Editing notebook" %>

<h1>Editing notebook</h1>

<%= render "form", notebook: @notebook %>

<br>

<div>
  <%= link_to "Show this notebook", @notebook %> |
  <%= link_to "Back to notebooks", notebooks_path %>
</div>

app/views/notebooks/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Notebooks" %>
<h1>Notebooks</h1>

<% if @notebooks.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Percent Complete</th>
        <th>Chapters Read</th>
      </tr>
    </thead>
    <tbody>
      <% @notebooks.each do |notebook| %>
        <%= render notebook %>
        <tr>
          <td colspan="5">
            <%= link_to "Show this notebook", notebook %>
            <%= button_to "Destroy this notebook", notebook, method: :delete, data: { confirm: "Are you sure you want to delete this notebook?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="no-notebooks">There are no notebooks till now. Create one using the button below.</p>
<% end %>

<%= link_to "New notebook", new_notebook_path %>

app/views/notebooks/new.html.erb
<% content_for :title, "New notebook" %>

<h1>New notebook</h1>

<%= render "form", notebook: @notebook %>

<br>

<div>
  <%= link_to "Back to notebooks", notebooks_path %>
</div>

app/views/notebooks/show.html.erb
<p style="color: green"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Percent Complete</th>
      <th>Chapters Read</th>
    </tr>
  </thead>
  <tbody>
    <%= render @notebook %>
  </tbody>
</table>


<div>
  <%= link_to "Edit this notebook", edit_notebook_path(@notebook) %> |
  <%= link_to "Back to notebooks", notebooks_path %>

  <%= button_to "Destroy this notebook", @notebook, method: :delete %>
</div>

<hr>
<h1>New chapter</h1>

<%= render 'chapters/form' %>

<hr>
<h1>Listing chapters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notebook.chapters.each do |chapter| %>
  <tr>
    <% if chapter.persisted? %>
      <td><%= chapter.name %></td>
      <td><%= chapter.description %></td>
      <td><%= chapter.status %></td>
      <td><%= link_to 'Show', [chapter.notebook, chapter] %></td>
      <td><%= link_to 'Edit', edit_notebook_chapter_path(chapter.notebook, chapter) %></td>
      <td><%= button_to 'Destroy', [chapter.notebook, chapter], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>